resources:
  - ../../base

namespace: prod

nameSuffix: -prod

patches:
  - target:
      kind: Ingress
      name: gitops-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: gitops.fawasam.in

replicas:
  - name: gitops-app
    count: 3

